_extends: .github
repository:
  description: The Forbidden Nix Flakes Doctrine
  homepage: https://github.com/infinitivewitch/flakegrimoire
  name: flakegrimoire
  topics: dotfiles, nix, nixos, nixos-configuration, flake, nix-flake, nixos-dotfiles
