name: deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        drv: [devShells]
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ github.token }}
          system-features = nixos-test benchmark big-parallel kvm recursive-nix
          substituters = https://cache.nixos.org https://colmena.cachix.org https://numtide.cachix.org https://nix-community.cachix.org https://infinitivewitch.cachix.org
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= colmena.cachix.org-1:7BzpDnjjH8ki2CT3f6GdOk7QAzPOl+1t3LvTLXqYcSg= numtide.cachix.org-1:2ps1kLBUWjxIneOy1Ik6cQjb41X0iXVXeHigGmycPPE= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= infinitivewitch.cachix.org-1:D0IprjPtIbtSlZc8vdsU12e1QgT68Goi4eDF+/olNVU=
    - uses: cachix/cachix-action@v12
      with:
        name: infinitivewitch
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix flake check --show-trace
    - run: nix develop --command treefmt --fail-on-change
    - run: nix flake archive --json | jq -r '.path,(.inputs|to_entries[].value.path)'
    - run: nix develop --command nix-build-uncached ./ci/${{ matrix.drv }}.nix
